[package]
name = "tui-rain-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.23"
crossterm = { version = "0.28.1", features = ["event-stream"] }
futures = "0.3.31"
ratatui = "0.29.0"
tokio = { version = "1.41.1", features = ["full"] }
tui-rain = "1.0.1"
